name: CI for schemademo

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  api-tests:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]
 
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci

    # run the npm build command (not used in our project)
    - run: npm run build --if-present 

    - run: npm run build-it
    - run: cd schedule-data-service && npm install && node index
    - run: npm install -g newman
    - run: npm run api
    
    
    


  deploy:
    name: "Deploy to main"
    needs: [api-tests]
    runs-on: ubuntu-latest
    steps:
      - name: Configure SSH
        run: |
          mkdir -p ~/.ssh/
          echo "$SSH_KEY" > ~/.ssh/dev.key
          chmod 600 ~/.ssh/dev.key
          cat >>~/.ssh/config <<END
          Host dev
            HostName $SSH_HOST
            User $SSH_USER
            Port $SSH_PORT
            IdentityFile ~/.ssh/dev.key
            StrictHostKeyChecking no
          END
        env:
          SSH_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          SSH_HOST: ${{ secrets.SSH_HOST }}
          SSH_USER: ${{ secrets.SSH_USER }}
          SSH_PORT: ${{ secrets.SSH_PORT }}          

     

      - name: Deploy from main 
        # Here 'ssh dev' is like run command which will be the same for every branch 
        # 'cd dev' here dev is the folder we make in the server (aws-terminal)
        run: ssh dev 'cd main/ && git fetch && git pull origin main'
        

      - name: Restart app (Important read how to link pm2 for sudoers https://stackoverflow.com/questions/62863080/github-actions-err-bash-line-3-npm-command-not-found )
        # Here 'dev' is the name of the app running by pm2
        run: ssh dev 'pm2 restart app'        